INSERT INTO product(name, stock_quantity, unit_price, category, category_gender, image_src) VALUES
('Polo Ralph Lauren', 100, 299, 'SHIRTS', 'MEN', '/images/Shirts/Shirt7.jfif'), 
('Dressberry', 70, 399, 'SHIRTS', 'WOMEN', '/images/Shirts/Shirt2.jfif'), 
('Cat & Jack', 50, 149, 'SHIRTS', 'KID', '/images/Shirts/Shirt1.jpg'),
('New Yorker', 80, 119, 'SHIRTS', 'UNISEX', '/images/Shirts/Shirt3.jpg'), 
('H&M', 30, 119, 'SHIRTS', 'UNISEX', '/images/Shirts/Shirt4.jpg'),
('Levis', 40, 349, 'JEANS', 'MEN', '/images/Jeans/Jeans6.jpg'), 
('Pepe Jeans', 0, 219, 'JEANS', 'WOMEN', '/images/Jeans/Jeans4.jpg'), 
('Denim', 78, 189, 'JEANS', 'KID', '/images/Jeans/Jeans7.jpg'),
('Wrangler', 54, 199, 'JEANS', 'WOMEN', '/images/Jeans/Jeans5.jpg'), 
('Denim', 65, 199, 'JEANS', 'KID', '/images/Jeans/Jeans8.jpg'),
('Nike', 40, 349, 'SHOES', 'MEN', '/images/Shoes/Shoes3.jpg'), 
('Miu Miu', 34, 219, 'SHOES', 'WOMEN', '/images/Shoes/Shoes4.jpg'), 
('Fendi', 78, 189, 'SHOES', 'KID', '/images/Shoes/Shoes9.jpg'),
('Jimmy Choo', 0, 199, 'SHOES', 'WOMEN', '/images/Shoes/Shoes5.jpg'), 
('Toms', 65, 199, 'SHOES', 'KID', '/images/Shoes/Shoes2.jpg'),
('Fendi', 18, 89, 'SHOES', 'KID', '/images/Shoes/Shoes1.jpg'),
('Tommy Hilfiger', 0, 109, 'SHOES', 'MEN', '/images/Shoes/Shoes6.jpg'), 
('Jimmy Choo', 46, 199, 'SHOES', 'UNISEX', '/images/Shoes/Shoes7.jpg'),
('Michael Kors', 64, 449, 'WATCHES', 'MEN', '/images/Watches/Watch5.jpeg'), 
('Bell & Ross', 39, 299, 'WATCHES', 'WOMEN', '/images/Watches/Watch1.jpg'), 
('Fossil', 65, 849, 'WATCHES', 'KID', '/images/Watches/Watch4.jpg'),
('Tommy Hilfiger', 76, 479, 'WATCHES', 'UNISEX', '/images/Watches/Watch2.jpg'), 
('Garmin', 0, 239, 'WATCHES', 'KID', '/images/Watches/Watch3.jpg');
